spring:
  kafka:
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="k874dhrh" password="pDi1gFVqoj2VKSyKvhjN0Zqep5IbnDaj";
      producer:
    consumer:
      bootstrap-servers: glider-01.srvs.cloudkafka.com:9094
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: glider-01.srvs.cloudkafka.com:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer