/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.foundvio.clouddb.model;

import com.huawei.agconnect.server.clouddb.request.CloudDBZoneObject;
import com.huawei.agconnect.server.clouddb.annotations.DefaultValue;
import com.huawei.agconnect.server.clouddb.annotations.NotNull;
import com.huawei.agconnect.server.clouddb.annotations.PrimaryKeys;

/**
 * Definition of ObjectType User.
 *
 * @since 2021-07-02
 */
@PrimaryKeys({"phoneId"})
public final class User extends CloudDBZoneObject {
    private String phoneId;

    @NotNull
    @DefaultValue(stringValue = "NA")
    private String givenName;

    @NotNull
    @DefaultValue(stringValue = "NA")
    private String familyName;

    @NotNull
    @DefaultValue(booleanValue = true)
    private Boolean isTracker;

    public User() {
        super(User.class);
        this.givenName = "NA";
        this.familyName = "NA";
        this.isTracker = true;

    }

    public void setPhoneId(String phoneId) {
        this.phoneId = phoneId;
    }

    public String getPhoneId() {
        return phoneId;
    }

    public void setGivenName(String givenName) {
        this.givenName = givenName;
    }

    public String getGivenName() {
        return givenName;
    }

    public void setFamilyName(String familyName) {
        this.familyName = familyName;
    }

    public String getFamilyName() {
        return familyName;
    }

    public void setIsTracker(Boolean isTracker) {
        this.isTracker = isTracker;
    }

    public Boolean getIsTracker() {
        return isTracker;
    }

}
